<?php

return [
    'home' => [
        'title' => 'Ride when you need to go',
        'eyebrow' => 'KarnaCab',
        'lede' => 'KarnaCab is Bihar mobility: rides, parcel, travel, bulk booking and corporate.',
        'template' => 'home',
        'nav_group' => 'primary',
        'nav_label' => 'Home',
    ],
    'rides' => [
        'title' => 'Rides',
        'eyebrow' => 'Vehicles',
        'lede' => 'Vehicle categories from the live catalog.',
        'template' => 'rides',
        'nav_group' => 'primary',
        'nav_label' => 'Rides',
    ],
    'about' => [
        'title' => 'About KarnaCab',
        'eyebrow' => 'Company',
        'lede' => 'One platform for customers, captains and partners.',
        'template' => 'legal',
        'nav_group' => 'company',
        'nav_label' => 'About',
    ],
    'how-it-works' => [
        'title' => 'How KarnaCab works',
        'eyebrow' => 'Guide',
        'lede' => 'Preview a route, then send a booking request.',
        'template' => 'legal',
        'nav_group' => 'company',
        'nav_label' => 'How it works',
    ],
    'safety' => [
        'title' => 'Safety',
        'eyebrow' => 'Trust',
        'lede' => 'Driver KYC and support on one platform.',
        'template' => 'legal',
        'nav_group' => 'company',
        'nav_label' => 'Safety',
    ],
    'local-cab' => [
        'title' => 'Local Cab',
        'eyebrow' => 'Ride',
        'lede' => 'City rides. Fares come from Admin fare rules.',
        'lead_type' => 'RIDE',
        'product_key' => 'LOCAL_CAB',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Local cab',
    ],
    'one-way' => [
        'title' => 'One Way',
        'eyebrow' => 'Ride',
        'lede' => 'Point-to-point trips. Quotes are calculated by the API.',
        'lead_type' => 'RIDE',
        'product_key' => 'ONE_WAY',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'One way',
    ],
    'round-way' => [
        'title' => 'Round Way',
        'eyebrow' => 'Ride',
        'lede' => 'Outbound and return. Extra KM follows Admin fare rules.',
        'lead_type' => 'RIDE',
        'product_key' => 'ROUND_WAY',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Round way',
    ],
    'rental' => [
        'title' => 'Rental',
        'eyebrow' => 'Ride',
        'lede' => 'Hourly packages from the live rental catalog.',
        'lead_type' => 'RIDE',
        'product_key' => 'RENTAL',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Rental',
    ],
    'schedule' => [
        'title' => 'Schedule',
        'eyebrow' => 'Ride',
        'lede' => 'Book a future pickup. Assignment windows are Admin settings.',
        'lead_type' => 'RIDE',
        'product_key' => 'SCHEDULE',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Schedule',
    ],
    'outstation' => [
        'title' => 'Outstation',
        'eyebrow' => 'Ride',
        'lede' => 'Intercity travel from catalog districts.',
        'lead_type' => 'RIDE',
        'product_key' => 'OUTSTATION',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Outstation',
    ],
    'airport' => [
        'title' => 'Airport',
        'eyebrow' => 'Transfer',
        'lede' => 'Airport pickup and drop. Policy from the ride catalog.',
        'lead_type' => 'RIDE',
        'product_key' => 'AIRPORT',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Airport',
    ],
    'railway' => [
        'title' => 'Railway',
        'eyebrow' => 'Transfer',
        'lede' => 'Station pickup and drop from the live catalog.',
        'lead_type' => 'RIDE',
        'product_key' => 'RAILWAY',
        'template' => 'service',
        'nav_group' => 'rides',
        'nav_label' => 'Railway',
    ],
    'parcel' => [
        'title' => 'Parcel',
        'eyebrow' => 'Delivery',
        'lede' => 'Local parcel. Types and prohibited goods come from Admin.',
        'lead_type' => 'PARCEL',
        'template' => 'service',
        'nav_group' => 'services',
        'nav_label' => 'Parcel',
    ],
    'bihar-parcel' => [
        'title' => 'Bihar Parcel',
        'eyebrow' => 'Delivery',
        'lede' => 'District-to-district parcel using the Admin parcel policy.',
        'lead_type' => 'BIHAR_PARCEL',
        'template' => 'service',
        'nav_group' => 'services',
        'nav_label' => 'Bihar parcel',
    ],
    'travel' => [
        'title' => 'Travel Packages',
        'eyebrow' => 'KarnaTravel',
        'lede' => 'Published packages from Admin KarnaTravel records.',
        'lead_type' => 'TRAVEL',
        'template' => 'travel',
        'nav_group' => 'services',
        'nav_label' => 'Travel',
    ],
    'bulk-booking' => [
        'title' => 'Bulk Booking',
        'eyebrow' => 'Events',
        'lede' => 'Multiple vehicles. Event types come from the bulk catalog.',
        'lead_type' => 'BULK',
        'template' => 'service',
        'nav_group' => 'services',
        'nav_label' => 'Bulk booking',
    ],
    'corporate' => [
        'title' => 'Corporate',
        'eyebrow' => 'Business',
        'lede' => 'Employee transport and GST billing enquiry.',
        'lead_type' => 'CORPORATE',
        'template' => 'service',
        'nav_group' => 'primary',
        'nav_label' => 'Corporate',
    ],
    'business' => [
        'title' => 'Business',
        'eyebrow' => 'Business',
        'lede' => 'Accounts, GST billing and volume travel for companies.',
        'lead_type' => 'CORPORATE',
        'template' => 'service',
        'nav_group' => 'company',
        'nav_label' => 'Business',
    ],
    'drive' => [
        'title' => 'Drive With Us',
        'eyebrow' => 'Captains',
        'lede' => 'Register as a driver. KYC documents are Admin settings.',
        'template' => 'register',
        'register_kind' => 'driver',
        'nav_group' => 'company',
        'nav_label' => 'Drive with us',
    ],
    'fleet-partner' => [
        'title' => 'Fleet Partner',
        'eyebrow' => 'Partners',
        'lede' => 'Operate multiple vehicles under one fleet account.',
        'lead_type' => 'FLEET',
        'register_kind' => 'fleet',
        'template' => 'service',
        'nav_group' => 'company',
        'nav_label' => 'Fleet partner',
    ],
    'franchise' => [
        'title' => 'Franchise',
        'eyebrow' => 'Network',
        'lede' => 'Apply for a district franchise. One active exclusive seat per district.',
        'lead_type' => 'FRANCHISE',
        'register_kind' => 'franchise',
        'template' => 'service',
        'nav_group' => 'primary',
        'nav_label' => 'Franchise',
    ],
    'advertise' => [
        'title' => 'Advertise With Us',
        'eyebrow' => 'KarnaCab Ads',
        'lede' => 'Register an advertiser account or send an enquiry.',
        'lead_type' => 'ADVERTISE',
        'register_kind' => 'advertiser',
        'template' => 'register',
        'nav_group' => 'company',
        'nav_label' => 'Advertise',
    ],
    'contact' => [
        'title' => 'Contact',
        'eyebrow' => 'Hello',
        'lede' => 'Send a support request. Stored as a lead in the KarnaCab API.',
        'lead_type' => 'SUPPORT',
        'template' => 'contact',
        'nav_group' => 'primary',
        'nav_label' => 'Contact',
    ],
    'support' => [
        'title' => 'Support',
        'eyebrow' => 'Help',
        'lede' => 'FAQs from the live help catalog.',
        'lead_type' => 'SUPPORT',
        'template' => 'support',
        'nav_group' => 'company',
        'nav_label' => 'Support',
    ],
    'terms' => [
        'title' => 'Terms & Conditions',
        'eyebrow' => 'Legal',
        'lede' => 'Terms for the public website, quotes and partner applications.',
        'template' => 'legal',
        'nav_group' => 'legal',
        'nav_label' => 'Terms',
    ],
    'privacy' => [
        'title' => 'Privacy Policy',
        'eyebrow' => 'Legal',
        'lede' => 'How the public website handles the information you type.',
        'template' => 'legal',
        'nav_group' => 'legal',
        'nav_label' => 'Privacy',
    ],
];
